os:
   edit: 'hx {{filename}}'
   editInTerminal: true
#added comment

keybinding:
  universal:
    prevItem-alt: 'i'
    nextItem-alt: 'e'
    prevBlock-alt: 'n'
    nextBlock-alt: 'o'
    scrollLeft: 'N'
    scrollRight: 'O'
    nextMatch: '='
    prevMatch: '-'
    new: 'k'
    edit: 'h'
    openFile: 'H'
    scrollUpMain-alt1: 'I'
    scrollDownMain-alt1: 'E'
    # scrollUpMain-alt2: '<c-i>'
    # scrollDownMain-alt2: '<c-e>'
    undo: 'l'
    redo: '<c-r>'
    diffingMenu: 'M'
    copyToClipboard: '<c-y>'
    filteringMenu: '<c-f>'

  files:
    ignoreFile: 'j'
  commits:
    # I can't use c-i for some reason so we are using these instead
    moveUpCommit: '<c-n>'
    moveDownCommit: '<c-o>'
    #we don't really need this and it collides with c-y our normal copy  
    copyCommitMessageToClipboard: ''
    openInBrowser: 'H'
  branches:
    viewGitFlowOptions: 'J'
    createPullRequest: 'h'
    viewPullRequestOptions: 'H'


